[package]
name = "ptj_sl"
version = "0.1.0"
authors = ["Myeongseon Choi <key262yek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
